version: '3'

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/evento-io
    depends_on:
      - mongo
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  mongo-data:
    driver: local